---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ZhaoKai.
--- DateTime: 2023/11/13 14:00
---
local M = {}

function M.init()
    M.config()
    M.refresh(75, 5)
end

function M.config()
    local g_neovide = {
        ['guifont'] = 'JetBrains Mono:h14',
        ['neovide_cursor_animation_length'] = 0.03,
        ['neovide_cursor_trail_size'] = 0.8,
        ['neovide_cursor_vfx_mode'] = "pixiedust",
        ['neovide_profiler'] = false,
        ['neovide_remember_window_size'] = true,
        ['neovide_transparency'] = 0.97,
        ['neovide_input_use_logo'] = true,
        ['neovide_floating_blur_amount_x'] = 2.0,
        ['neovide_floating_blur_amount_y'] = 2.0,
        ['neovide_hide_mouse_when_typing'] = true,
        ['neovide_theme'] = 'auto',
        ['neovide_input_ime'] = true,
        ['neovide_no_idle'] = true,
        -- 退出需要确认
        ['neovide_confirm_quit'] = true,
        -- 是否全屏
        ['neovide_fullscreen'] = false,
        -- 记住以前窗口的大小
        ['neovide_remember_window_size'] = true
    }
    for k, v in pairs(g_neovide) do
        vim.g[k] = v
    end
end

function M.background()
    -- Helper function for transparency formatting
    -- only macOS
    local alpha = function()
        return string.format("%x", math.floor(255 * vim.g.transparency or 0.8))
    end
    -- g:neovide_transparency should be 0 if you want to unify transparency of content and title bar.
    vim.g.neovide_transparency = 0.0
    vim.g.transparency = 0.8
    vim.g.neovide_background_color = "#0f1117" .. alpha()
end

-- 设置fps
function M.refresh(run_fps, free_fps)
    -- 设置刷新率
    vim.g.neovide_refresh_rate = run_fps
    -- 空闲刷新率
    vim.g.neovide_refresh_rate_idle = free_fps
end

return M