---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ZhaoKai.
--- DateTime: 2023/11/14 16:47
---
---
return {
    { "rebelot/kanagawa.nvim",
      event = "VimEnter",
      config = function()
          vim.cmd("colorscheme kanagawa")
      end,
    }
}
